### ISSUE TITLE
Select specific home for the somfy plugin

### ISSUE THREAD

**Issue by vincentdreano** [alxscms/homebridge-somfy-protect#2] opened 2020-11-28 15:32 UTC
Hi !

Thank you for your plugin, he is working great, but the specific bug you have described is real 👍 

I have my own alarm, and my father's one. But right now, I am control their alarm and not my own.
Is it possible to specify the home I want to configure ? For example by the Name ?

Best regards !

**Comment by vincentdreano** [comment] 2020-11-28 17:30
Hi @alxscms,

You will be able to find a purpose of solution on my temp repo :
https://github.com/vincentdreano/homebridge-somfy-protect-multi

You will be able to take what you want and improve my code.

**Comment by alxscms** [comment] 2021-02-02 10:47
I'll have a look into that soon :) thanks for the suggestion !

**Comment by amery78** [comment] 2021-09-05 10:49
Hello, thank you for your excellent plugin !
I would definitely need the possibility to select the home as I have two different homes in Somfy.
I don't know how to use the proposed repo...
Are you planning to update or expose a new plugin ?

thank you !

Axel

**Comment by alxscms** [comment] 2021-11-22 16:49
Hey guys, I have made changes to the plugin so that you can configure which home to use using the new attribute `siteId` in the config. If your somfy account has more than one home (or "site" as they call it) the list should be logged by the plugin with for each home, the name and its ID.

@vincentdreano if this update works well for you, it would be great if you could remove the fork you've made as it does not bring more feature anymore :) thanks a lot !

**Comment by vincentdreano** [comment] 2021-11-23 11:45
Hey alxcms,

I still have an issue with your latest update (Hombegridge 1.3.8, plugin 1.1.0).

When I re-install the plugin with no SiteId configured, I cannot access to the SiteId list in the log.
Moreover, I have some error in the logs 👍 

```
[11/23/2021, 12:39:20 PM] [Somfy Protect] Initializing SomfyProtect accessory...
[11/23/2021, 12:39:20 PM] Homebridge v1.3.8 (HAP v0.9.7) (Homebridge 932A) is running on port 52549.
(node:1629) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'log' of undefined
    at warn (/usr/local/lib/node_modules/homebridge/src/logger.ts:135:10)
    at HomekitSomfySite.initialize (/homebridge/node_modules/homebridge-somfy-protect/src/lib/homekit_somfy_site.ts:62:7)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1629) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1629) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

If I try to put anny SiteId value, i'll obtain this logs file
```
[11/23/2021, 12:43:50 PM] Homebridge v1.3.8 (HAP v0.9.7) (Homebridge 932A) is running on port 52549.
(node:2284) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'site_id' of undefined
    at HomekitSomfySite.initialize (/homebridge/node_modules/homebridge-somfy-protect/src/lib/homekit_somfy_site.ts:62:92)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2284) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2284) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by alxscms** [comment] 2021-11-23 17:20
Hi vincent!

Thanks for your feedback. Could you try using this beta version [1.1.1-beta.1](https://www.npmjs.com/package/homebridge-somfy-protect/v/1.1.1-beta.1) to see if you have the same issues ?
I have fixed the second error you mentioned. However I don't understand why the first one is occurring. I do not reproduce the errors myself that's why it's pretty hard to debug.

**Comment by alxscms** [comment] 2021-11-23 22:45
I might have a lead for the first bug. Are you using hoobs?

**Comment by vincentdreano** [comment] 2021-11-24 09:06
Hi,

I don't things so, I am using a docker container working on my Synology :
https://github.com/oznu/docker-homebridge

I have not tested yet the beta 1 for now because I can't select this version on my production server (I think), I will try on my computer later this week.

**Comment by alxscms** [comment] 2021-11-24 15:32
Hi, thanks for your reply. I think I have found why you had the `Cannot read property 'log' of undefined` error, it was due to a wrong context while calling the log function. This should be fixed in the new beta version I just uploaded : [1.1.1-beta.2](https://www.npmjs.com/package/homebridge-somfy-protect/v/1.1.1-beta.2).
Test when you can, thanks a lot :)

**Comment by vincentdreano** [comment] 2021-11-25 17:28
Hi alxscms,

I have just tested the latest beta and everythings is now working for me.

Thank you for the fix :)

**Comment by alxscms** [comment] 2021-11-26 10:46
Perfect ! Enjoy the plugin :)

**Closed as completed by alxscms** 2021-11-26 10:46 UTC
